[package]
name = "goodreads-graphql"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"

aws-config = "0.54.1"
aws-credential-types = "0.54.1"
aws-http = "0.54.1"
aws-sdk-appsync = "0.24.0"
aws-sdk-cognitoidentity = "0.24.0"
aws-sdk-s3 = "0.24.0"
aws-sig-auth = "0.54.1"
aws-sigv4 = "0.54.1"
aws-smithy-async = { version = "0.54.4", features = ["rt-tokio"] }
aws-smithy-client = { version = "0.54.3", features = ["rustls", "hyper-rustls", "hyper", "serde"] }
aws-smithy-http = "0.54.3"
aws-smithy-http-tower = "0.54.4"
aws-types = "0.54.1"
bytes = { version = "1.4.0", features =["serde"] }

http = "0.2.9"
hyper = "0.14.24"

reqwest = { version = "0.11.14", features = ["cookies", "brotli", "gzip", "json", "rustls"] }

serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
thiserror = "1.0.38"

tokio = { version = "1.25.0", features = ["full"] }
tower = { version = "0.4.13", features = ["full"] }
tower-http = "0.3.5"
tracing = { version = "0.1.37", features = ["async-await"] }
